### ISSUE TITLE
Elegant Free Theme Version 2.2.0 Bug

### ISSUE THREAD

**Issue by kimscrochets** [wpexplorer/wpex-elegant#1]
Hi AJ, thank you for responding...I wasn't sure where to report the bug I'm having. WP said there was a new version of the Elegant theme (2.2.0), so when I looked, I already had that version. But I went ahead and updated and everything went fine. But, when I went to "activate" my child theme, WP said the parent theme was missing. And, my website didn't load. So to fix this, I created a new child theme. That went fine but then WP says I need to install the elegant version 2.2.0 again. I attached the screenshot for you to see. It's confusing me :), hopefully I'm not confusing you. How do I fix this?
![capture](https://user-images.githubusercontent.com/29613045/27403763-7c738ec6-5680-11e7-99b2-e2039b934feb.JPG)

**Comment by wpexplorer** [comment]
@kimscrochets - So it only shows the update available when you are using the child theme correct? If so...I think the update I am pushing out right now will fix it. You can apply the fix manually if you want based on the github changes (inc/updates.php).

**Comment by wpexplorer** [comment]
Just tested and 2.2.1 seems fixed. I'll be closing the ticker, if you still have issues though let me know.

**Comment by kimscrochets** [comment]
That update worked AJ! Thank you!

**Comment by wpexplorer** [comment]
@kimscrochets No, thank you for reporting the bug!!
