### ISSUE TITLE
Problem with menu on android

### ISSUE THREAD

**Issue by fmagli** [wpexplorer/wpex-elegant#2]
Hi guys, as I red on the creative market comments, "Sounds like a bug with the device, can you let me know what device you are using? This doesn't happen on iPhones/Tablets.".
I try the website with android, with iphone yes, no problem. 
The vertical scroll of the menu is strange. I mean, if you put at least 30 items in the menu (list or sub-list) after 2 second scrolling it disappears.

I'm looking for a solutions.

Have a nice Day

F

**Comment by wpexplorer** [comment]
@fmagli - Sorry for the delayed response. I'm going to upload an updated version of the theme in a few minutes and hopefully it fixes the issue ;)

**Comment by wpexplorer** [comment]
Submitted the update, should be fixed now. If not let me know!
