### ISSUE TITLE
Potential issue with Theme/Documentation?

### ISSUE THREAD

**Issue by Liquidream** [wpexplorer/wpex-elegant#3]
Firstly, thanks for the theme - it's great :smile: 

However, after a fresh install of the theme (v2.2.2) and using exactly the same pictures as your demo site - my Portfolio thumbnails(?) are not displaying in the same proportions/ratio as the demo.  I can confirm that I have no custom CSS and this still happens.

**Demo Site:**
![portfolio-elegant](https://user-images.githubusercontent.com/2211678/30492800-a6a3d744-9a39-11e7-892c-2e6008bc7a6d.png)

**My Site** _(thumbnails noticeably smaller in height - for some reason):_
![portfolio-mine](https://user-images.githubusercontent.com/2211678/30492809-af1e54e4-9a39-11e7-854d-8131e9ac2ffa.png)

I'm wondering whether your Documentation is missing a step and that there are perhaps some other global Wordpress settings that I need to change (e.g. Media Thumbnail size) in order to achieve the same results?

Everything else appears to work fine.  Ultimately, what I would like to happen is for there to be consistent height across all Portfolio thumbnails (scaling/cropping accordingly) - which is what your demo sight *seems* to be doing, but I can't be certain.

Many thanks in advance.

**Comment by wpexplorer** [comment]
@Liquidream - Just like any other theme that uses native WordPress thumbnails you'll want to install and run a Regeneration plugin for your thumbnails. I prefer this one - https://wordpress.org/plugins/force-regenerate-thumbnails/
