### ISSUE TITLE
Adding Staff is not possible as it is unavailable

### ISSUE THREAD

**Issue by bchipre** [wpexplorer/wpex-elegant#4]
![staff_missing](https://user-images.githubusercontent.com/33052366/31930303-e9ed8846-b8bc-11e7-94f0-9ca243cfd502.JPG)
Adding staff members in not possible in the wpex-elegant Theme since it doesn't show up on the left side of the word press editing page.

**Comment by wpexplorer** [comment]
The only reason it wouldn't show up is if it was disabled in the Customizer, please check your Customizer settings.
