### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by dgsunesen** [wpexplorer/wpex-elegant#7]
Hi there,

I'm starting to see this error:

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/slj-sport.dk/public_html/wp-content/themes/wpex-elegant/inc/classes/custom-metaboxes-and-fields/init.php on line 746

I'm pretty sure it happened after I updated my wordpress to one of the latest version 5.1.x

I see this is an issue on multiple websites using this theme.

**Comment by froggobaggins** [comment]
Same issue here 

Warning: count(): Parameter must be an array or an object that implements Countable in /wp-content/themes/wpex-elegant/functions/meta/init.php on line 750

Warning: count(): Parameter must be an array or an object that implements Countable in /wp-content/themes/wpex-elegant/functions/meta/init.php on line 750

Warning: count(): Parameter must be an array or an object that implements Countable in /wp-content/themes/wpex-elegant/functions/meta/init.php on line 750

Warning: count(): Parameter must be an array or an object that implements Countable in /wp-content/themes/wpex-elegant/functions/meta/init.php on line 750

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/themes/wpex-elegant/functions/meta/init.php:750) in /wp-admin/includes/misc.php on line 1144

**Comment by wpexplorer** [comment]
@dgsunesen @froggobaggins - Thanks for the heads up. These are notices in PHP 7+

I just pushed out an update which you can grab here or redownload from the main page - https://www.wpexplorer.com/elegant-free-wordpress-theme/

I will work on releasing a plugin on WordPress.org that you can enable on any site using one of my themes to provide built-in updates. So keep an eye out for that.

If you have any other issues or requests let me know!

- AJ
