### ISSUE TITLE
Remove support for "Less than IE9", or include html5.js.

### ISSUE THREAD

**Issue by lewisik** [wpexplorer/wpex-elegant#8]
on header.php , there's
`	
`
yet html5.js doesn't exists in the directory.

Solution would be
1) remove support for IE8 and less on header.php
2) include html5.js or html5shiv.js and edit the header.php

**Comment by wpexplorer** [comment]
@lewisik  - Thank you for letting me know. I will try and push out an update tomorrow. The best solution is to remove the code from the header, add the html5.js file to the theme and load it via wp_enqueue_script.

I will reply back here again once the update is ready. Thank you again for reporting the error.

**Comment by lewisik** [comment]
awesome!
